[workspace]
members = ["contrib/richclip-labeld", "richclip-wayland"]
resolver = "3"

[package]
name = "richclip"
version = "0.1.1"
edition = "2024"

[lib]
name = "richclip"
path = "src/lib.rs"

[[bin]]
name = "richclip"
path = "src/bin/richclip.rs"

[dependencies]
anyhow = "1.0.102"
blake3 = "1.8.5"
clap = { version = "4.6.1", features = ["derive"] }
directories = "6.0.0"
humantime = "2.3.0"
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "webp", "bmp"] }
rusqlite = { version = "0.37", features = ["bundled"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
thiserror = "2.0.18"
time = { version = "0.3.47", features = ["formatting", "parsing", "serde-well-known"] }
uuid = { version = "1.23.2", features = ["v7", "serde"] }

[dev-dependencies]
assert_cmd = "2.2.2"
predicates = "3.1.4"
tempfile = "3.27.0"
